version: "3"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env

  web:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8000
